### ISSUE TITLE
preprocessing output format & monolingual word embedding training detail

### ISSUE THREAD

**Issue by qimang** [Pzoom522/ECL-dict#2]
#### 2.按照CSDN- 飞桨paddlepaddle的那篇文章，我没太理解“SVD+PIM”训练的是濒危语料还是故事会中文语料，还是说两者都是采用同一种训练方式

#### 2. according to the article of CSDN- flying paddle paddlepaddle, I didn't quite understand whether "SVD+PIM" training is endangered corpus or story Chinese corpus, or both are using the same training method.

**Comment by Pzoom522** [comment]
Hi,

Thanks for your attention on this project! Regarding your questions,

> The training text format obtained by OCR reading the story corpus

The processed format is one sentence per line + segmented, such as
```
这 是 一句 处理 后 的 《 故事会 》 语料 。
这 是 另外 一句 。
``` 

However, due to copyright issues (we're still trying to solve them though), currently we are unable to release the corpus. Please stay tuned!

> whether "SVD+PMI" training is for endangered corpus or story Chinese corpus

We applied unified word embedding training algorithm on both sides.

**Comment by qimang** [comment]
Thank you for your reply. It's very helpful to me。

**Comment by qimang** [comment]
There is another question, I would like to ask is this all the code？

**Comment by qimang** [comment]
OK, thank you for your reply
